### PR TITLE
control.tpl: fix maintainer/uploader for DPT profile

### PR DESCRIPTION
**Pull request by gagath**
Packages in the DPT should have the DPT as a maintainer, and then
distinct uploaders with one entry for each person that interracts with
the package under the umbrella of the DPT.

### CODE REVIEW

**Comment by sandrotosi** [comment]
i prefer to keep it as it is right now

**Comment by gagath** [comment]
> i prefer to keep it as it is right now

For my knowledge: is my assumption that *packages must have the DPT in the maintainers field* wrong, or that you prefer to keep this for now even if it seems to conflict with the DPT’s policy?

**Comment by sandrotosi** [comment]
in the [debian python policy](https://www.debian.org/doc/packaging-manuals/python-policy/) there's no reference on how to set Maintainer/Uploaders fields. It is instead described in the [Debian Python Team policy](https://salsa.debian.org/python-team/tools/python-modules/blob/master/policy.rst#maintainership)

**Comment by gagath** [comment]
> in the [debian python policy](https://www.debian.org/doc/packaging-manuals/python-policy/) there's no reference on how to set Maintainer/Uploaders fields. It is instead described in the [Debian Python Team policy](https://salsa.debian.org/python-team/tools/python-modules/blob/master/policy.rst#maintainership)

Thanks!

Here is the paragraph that details the two possibilities from the page you mentioned:

> Team in Maintainers is a strong statement that fully collaborative
maintenance is preferred. Anyone can commit to the Git repository and upload
as needed. A courtesy email to Uploaders can be nice but not required.

> Team in Uploaders is a weak statement of collaboration. Help in
maintaining the package is appreciated, commits to the Git repository are
freely welcomed, but before uploading, please contact the Maintainer for
the green light.

So far I was only aware of the first possibility. Thanks for the heads up! :+1:

**Pull request closed without merging**
